config/routes.rb
Rails.application.routes.draw do

root 'breeders#index'

  get 'pages/about'

  get 'pages/contact'

    resources :breeders do
      collection do
      get 'search'
    end
  end
end

app/models/breeder.rb
class Breeder < ActiveRecord::Base
	searchkick
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breeders_controller.rb
class BreedersController < ApplicationController
  before_action :set_breeder, only: [:show, :edit, :update, :destroy]

def search
  if params[:search].present?
    @breeders = Breeder.search(params[:search])  
else
   @breeders = Breeder.all
end
end

    # GET /breeders
  # GET /breeders.json
  def index
    @breeders = Breeder.all
  end

  # GET /breeders/1
  # GET /breeders/1.json
  def show
  end

  # GET /breeders/new
  def new
    @breeder = Breeder.new
  end

  # GET /breeders/1/edit
  def edit
  end

  # POST /breeders
  # POST /breeders.json
  def create
    @breeder = Breeder.new(breeder_params)

    respond_to do |format|
      if @breeder.save
        format.html { redirect_to @breeder, notice: 'Breeder was successfully created.' }
        format.json { render :show, status: :created, location: @breeder }
      else
        format.html { render :new }
        format.json { render json: @breeder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breeders/1
  # PATCH/PUT /breeders/1.json
  def update
    respond_to do |format|
      if @breeder.update(breeder_params)
        format.html { redirect_to @breeder, notice: 'Breeder was successfully updated.' }
        format.json { render :show, status: :ok, location: @breeder }
      else
        format.html { render :edit }
        format.json { render json: @breeder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeders/1
  # DELETE /breeders/1.json
  def destroy
    @breeder.destroy
    respond_to do |format|
      format.html { redirect_to breeders_url, notice: 'Breeder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breeder
      @breeder = Breeder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def breeder_params
      params.require(:breeder).permit(:name, :street, :address, :suburb, :state, :postcode, :telephone, :number, :website)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeders_helper.rb
module BreedersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/breeders/_form.html.erb
<%= form_for(@breeder) do |f| %>
  <% if @breeder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@breeder.errors.count, "error") %> prohibited this breeder from being saved:</h2>

      <ul>
      <% @breeder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :suburb %><br>
    <%= f.text_field :suburb, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %><br>
    <%= f.text_field :state, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :postcode %><br>
    <%= f.number_field :postcode, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/breeders/edit.html.erb
<h1>Editing Breeder</h1>

<%= render 'form' %>

<%= link_to 'Show', @breeder %> |
<%= link_to 'Back', breeders_path %>

app/views/breeders/index.html.erb
<div class="jumbotron">
  <h2>We are the best pet breeder search tool in Australia.</h2><br/>
  <h3>Find a dog or cat breeder by breed or location.</h3>
</div>

<h1>Find by breed or location</h1>
<p>(e.g. Poodle, NSW, 2000)</p>
    <%= form_tag search_breeders_path, method: :get, class: "form-group" do %>
  <%= text_field_tag :search, params[:search], class: "form-control" %></br>
    <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
   <% end %>

<div>
<h3> All breeders </h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Suburb</th>
      <th>State</th>
      <th>Postcode</th>
      <th>Telephone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breeders.each do |breeder| %>
      <tr>
        <td><%= breeder.name %></td>
        <td><%= breeder.address %></td>
        <td><%= breeder.suburb %></td>
        <td><%= breeder.state %></td>
        <td><%= breeder.postcode %></td>
        <td><%= breeder.telephone %></td>
        <td><%= breeder.website %></td>
        <td><%= link_to 'Show', breeder %></td>
        <td><%= link_to 'Edit', edit_breeder_path(breeder) %></td>
        <td><%= link_to 'Destroy', breeder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breeder', new_breeder_path %>

app/views/breeders/new.html.erb
<h1>New Breeder</h1>

<%= render 'form' %>

<%= link_to 'Back', breeders_path %>

app/views/breeders/search.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Suburb</th>
      <th>State</th>
      <th>Postcode</th>
      <th>Telephone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breeders.each do |breeder| %>
      <tr>
        <td><%= breeder.name %></td>
        <td><%= breeder.address %></td>
        <td><%= breeder.suburb %></td>
        <td><%= breeder.state %></td>
        <td><%= breeder.postcode %></td>
        <td><%= breeder.telephone %></td>
        <td><%= breeder.website %></td>
        <td><%= link_to 'Show', breeder %></td>
        <td><%= link_to 'Edit', edit_breeder_path(breeder) %></td>
        <td><%= link_to 'Destroy', breeder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/breeders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @breeder.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @breeder.address %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @breeder.suburb %>
</p>

<p>
  <strong>State:</strong>
  <%= @breeder.state %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @breeder.postcode %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @breeder.telephone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @breeder.website %>
</p>

<%= link_to 'Edit', edit_breeder_path(@breeder) %> |
<%= link_to 'Back', breeders_path %>

app/views/layouts/_bootstrap.html.erb
  <title>breederapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

app/views/layouts/_footer.html.erb
<nav aria-label="...">
  <ul class="pagination">
    <li class="disabled">
      <span>
        <span aria-hidden="true">&laquo;</span>
      </span>
    </li>
    <li class="active">
      <span>1 <span class="sr-only">(current)</span></span>
    </li>
    ...
  </ul>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">BreederDemo</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><a href="/pages/about">About</a></li>
	        <li><a href="/pages/contact">Contact</a></li>
	   	      </ul>
	     
	     	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

app/views/layouts/_pagination.html.erb
<nav aria-label="...">
  <ul class="pagination">
    <li class="disabled">
      <span>
        <span aria-hidden="true">&laquo;</span>
      </span>
    </li>
    <li class="active">
      <span>1 <span class="sr-only">(current)</span></span>
    </li>
    ...
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<%= render "layouts/bootstrap" %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/navbar" %>
	<div class="container-fluid">
	<%= yield %>
	<%= render "layouts/footer" %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>